
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://yrmthwhfzyybshvbojyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybXRod2hmenl5YnNodmJvanl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTMxMzAsImV4cCI6MjA1ODQ4OTEzMH0.Ee1F7BqjyFve6DZSfK2yXfgsGlDIHXSLk1AjZIwAFSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
